### ISSUE TITLE
Some flags are not 4:3

### ISSUE THREAD

**Issue by remyberda** [weglot/languages#25]
6 flags ne sont pas au bon rations ici : 
https://github.com/weglot/languages/tree/master/images/flags/4x3 (tous sauf eo.svg)

Par exemple le fr-ca est en 3:2
https://github.com/weglot/languages/blob/master/images/flags/4x3/fr-ca.svg

Du coup ça se repercute sur le dashboard et sur les sites comme ici :
<img width="389" alt="Capture d’écran 2021-08-20 à 17 51 15" src="https://user-images.githubusercontent.com/22366468/130259968-9810a7cb-6cf5-43d0-8859-a538e31b0f65.png">

Il faut remplacer les 6 flags par ceux là, que j'ai mis au bon format normalement
[flags.zip](https://github.com/weglot/languages/files/7022718/flags.zip)

**Comment by nico2che** [comment]
Fixed with https://github.com/weglot/languages/commit/1a0ee18713c1a24aed17c14a30fb53406e309aa1
