### ISSUE TITLE
Delete dist

### ISSUE THREAD

**Issue by nico2che** [weglot/languages#39]
A priori si t'as pu valider le .npmignore sur brokk, on pourra potentiellement

     - Supprimer le dist
     - Supprimer le workflow qui check le dist à jour
     - Mettre dist dans le gitignore
     - Ajouter un npmignore
     - Laisser le publish build le dist

_Originally posted by @VincentLanglet in https://github.com/weglot/languages/pull/38#pullrequestreview-1703884473_

on est bons côté intés

**Comment by VincentLanglet** [comment]
cc @floranpagliai

**Comment by VincentLanglet** [comment]
Closed by https://github.com/weglot/languages/pull/48
